language: generic
sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

# build test images
before_install:
  # GCP credential setup
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  # install GCP dependencies
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-369318 
  - gcloud config set compuete/zone us-west1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  #build testing image
  - docker build -t dsknudsen/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run -e CI=true dsknudsen/react-test npm run test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main

